### ISSUE TITLE
Eroors faced while exporting .blend file to .glb

### ISSUE THREAD

**Issue by send2jithu** [donmccurdy/three-gltf-viewer#243] opened 2021-02-13 07:29 UTC
Hi, so I have been trying to do some animations using Blender for a project of mine and tried to export the files in .glb file format but I have been getting some sort of random errors when I view these animations, like the components won't follow the required path or sometimes may be deformed. The problem here is that these errors are not exactly consistent meaning that trying to export multiple times just ends up giving different errors.

The animation basically consists of each component scaling up from zero and then joining with another. Like this, a whole assembly is created. I do this by preparing the assembly in Fusion 360, bring it into blender as an .fbx file. Now an armature is setup and the animation is done so that it looks like each piece flies off the model and dissapears. Now I simply flip the timeline by selecting the keyframes and scaling to -1. I've tried exporting to at each individual step to find that this flipping the keyframes causes the issue.

But now I see that however I try even without this 'inverting the timeline' step and directly doing the animations backwards is not woking out.

Please find the attachments...these are some of the errors I find while trying to view the .glb file.

Screenshot 2021-02-12 163029

Screenshot 2021-02-12 163050

If you can help me out in any way it would be much appreciated. You can find the blend file I created and the exported glb file in the drive link below.

https://drive.google.com/drive/folders/1KCFb-8UQ6Z48PFNJ8hG1g7I3Wjn6Ad4D?usp=sharing

**Comment by donmccurdy** [comment] 2021-02-13 19:51
Duplicate of https://github.com/donmccurdy/three-gltf-viewer/issues/242 — did you mean to open this bug on https://github.com/KhronosGroup/glTF-Blender-IO instead, perhaps?

**Closed by donmccurdy** 2021-02-13 19:51 UTC
