### ISSUE TITLE
glTF viewer broken?

### ISSUE THREAD

**Issue by randolchance** [donmccurdy/three-gltf-viewer#123] opened 2018-11-29 20:22 UTC
Hey, was fiddling with your glTF viewer the other day. I was very impressed!

But I've gone back to play with it the past two days and now it reports:

"Invalid JSON data. Parser output: FormatException: SyntaxError: Unexpected token < in JSON at position 6"

I've tried about a dozen different glTF (2.0) files and they all say the same thing. I would suspect it's a PEBKAC issue on my end, except using it is so easy that it's difficult to believe I'm messing something up.

Any insight you care to provide on this issue would be most generous.

Thanks!

**Comment by donmccurdy** [comment] 2018-11-29 20:30
Hm, you're the second person to report this but I can't reproduce it... do you see any errors in the JS console? What format of glTF are you using (ZIP, .glb, .gltf, ...)? And are you dragging it into the window or using the file upload button? Browser and OS may also be helpful.

**Comment by randolchance** [comment] 2018-11-30 13:38
Chrome:  Version 70.0.3538.110 (Official Build) (64-bit)

OS: Windows 10 Version 1803 (OS build 17134.407)

Console says:

bundle.js?v=r98:68087 SyntaxError: Unexpected token < in JSON at position 6
    at JSON.parse (<anonymous>)
    at GLTFLoader.parse (bundle.js?v=r98:62662)
    at Object.onLoad (bundle.js?v=r98:62580)
    at XMLHttpRequest.<anonymous> (bundle.js?v=r98:46391)

I both dragged and opened the file with the button. I went here
<https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck>
(KhronosGroup)
just now and tried every type of duck model in a glTF format, both dragging
and uploading with the button. All of them generated the same error.

If there's any more info I can provide just let me know.

**Comment by randolchance** [comment] 2018-11-30 13:39
Even the .glb version yields the same error.

**Comment by donmccurdy** [comment] 2018-11-30 18:05
Can you attach the file you've downloaded as a ZIP? You can drag ZIP files into GitHub comments. I still can't reproduce this. 🤔

**Comment by donmccurdy** [comment] 2018-11-30 18:40
There is a problem with this file — if you open it up, you'll see it contains the HTML from the GitHub page, and not the file itself:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
  <!-- ... -->
```

Perhaps you pressed "save" on the page before viewing the raw version? Or perhaps GitHub had a bug, you're the second person to run into this issue yesterday...

FWIW I made a browser extension to quickly open glTF files from GitHub in this viewer: https://github.com/donmccurdy/glTF-Browser-Extension

**Comment by randolchance** [comment] 2018-11-30 19:30
lol

welp then it is a PEBKAC issue

I'm sorry to have wasted your time, Don.

Though I've sourced some proper .gltf files now, and I'm still not able to
get things going. I'm probably doing something silly again.

This time I went here <https://sketchfab.com/features/gltf> and downloaded
their .zip files. Tried opening both the .zip and the .gltf for "Buster
drone" and "Adam head". What am I missing this time? :P

**Comment by randolchance** [comment] 2018-11-30 19:37
Dragging and dropping in the folders of the extracted zip files for those two I mentioned (adamHead & BusterDrone) works.

**Comment by donmccurdy** [comment] 2018-11-30 20:01
So the ZIP isn't working, but the folder is? I'm not sure why that would be, but the ZIP files do take a _long_ time to unzip for me. 😅

**Comment by donmccurdy** [comment] 2018-12-07 17:31
Closing, LMK if you're still having any trouble though.

**Closed by donmccurdy** 2018-12-07 17:31 UTC
