### ISSUE TITLE
 normal maps using OpenGL was displayed incorrectly in gltf viewer

### ISSUE THREAD

**Issue by sandyLee67** [donmccurdy/three-gltf-viewer#160] opened 2019-08-01 03:16 UTC
Hello， :)
We found normal maps using OpenGL format was displayed incorrectly in this platform（https://gltf-viewer.donmccurdy.com/）. As shown below, we can see obvious seam in OpenGL normal while the texture looks good in DirectX. 

[](url)
![image](https://user-images.githubusercontent.com/53055009/62263144-c14c5f00-b44d-11e9-8693-51da2bb0def2.png)

**Comment by donmccurdy** [comment] 2019-08-02 19:04
What tool are you exporting from? Is that Substance Painter?

OpenGL normals are supposed to work, and DirectX normals are _not_ supposed to work – glTF requires the right-handed convention. So this viewer is unfortunately doing the opposite now, which is a bug, and I think this is caused by https://github.com/mrdoob/three.js/issues/11438.

If your exporter allows you to include vertex tangents when exporting, that may allow you to work around the issue in the meantime.

**Comment by sandyLee67** [comment] 2019-08-22 05:14
Hello,
I find it seems that this issue still exists.So, do you know how soon the BUG is expected to be fixed? :）

thank you！

**Comment by donmccurdy** [comment] 2019-08-22 05:21
@sandyLee67 No, I don't know when this will be fixed. You can avoid the problem by exporting tangents in the model, if your export tool supports it.

**Comment by donmccurdy** [comment] 2020-01-29 18:01
I believe this was fixed by https://github.com/mrdoob/three.js/issues/11438. If you are still seeing the issue, please provide examples to reproduce the problem.

**Closed by donmccurdy** 2020-01-29 18:01 UTC
Labels: bug
