### ISSUE TITLE
Bounding box incorrect for scaled gltf exported from blender

### ISSUE THREAD

**Issue by benolayinka** [donmccurdy/three-gltf-viewer#192] opened 2020-04-17 19:58 UTC
I applied some animations in Mixamo to a mesh I created Blender, and in the FBX files that came back, my mesh unfortunately has a scale of 11.x and the armature a scale of 0.010. The animations still look and play fine in Blender, and also work in the Babylon sandbox, but in your GLTF viewer, the mesh is HUGE! You have to look directly upwards to see it, because you're below the foot of my character.

<img width="1277" alt="Screenshot 2020-04-17 at 21 55 23" src="https://user-images.githubusercontent.com/6963436/79608957-2805cb80-80f6-11ea-9a45-ecba77ae0305.png">

I copied the source from your repo and when I make the bounding box viewable, I see that it's tiny compared to the mesh.

Here's the gltf and blend files
[coach.zip](https://github.com/donmccurdy/three-gltf-viewer/files/4494991/coach.zip)

**Comment by donmccurdy** [comment] 2020-04-17 23:53
I think the underlying issue is https://github.com/mrdoob/three.js/issues/14499 or https://github.com/mrdoob/three.js/issues/11991 .... the viewer is unable to account for skinning when choosing the initial viewport.

**Comment by donmccurdy** [comment] 2020-04-17 23:53
Closing as a duplicate of https://github.com/donmccurdy/three-gltf-viewer/issues/147.

**Closed by donmccurdy** 2020-04-17 23:53 UTC
Labels: bug
